# Generated by Django 2.2.28 on 2022-06-29 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20220629_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsignup',
            name='GENDER',
        ),
    ]
