# Generated by Django 2.2.28 on 2022-06-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220623_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('mail', models.EmailField(default='user@email.tld', max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='StudentReg',
        ),
    ]
