# Generated by Django 2.2.28 on 2022-06-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220628_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsignup',
            name='GENDER',
            field=models.BooleanField(default=False),
        ),
    ]
